/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCarInSchedule: typeof import('./components/addCarInSchedule.vue')['default']
    AddModifyVehicle: typeof import('./components/AddModifyVehicle.vue')['default']
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Carousel: typeof import('./components/Carousel.vue')['default']
    CartButton: typeof import('./components/cartButton.vue')['default']
    ChatInput: typeof import('./components/ChatInput.vue')['default']
    ChatInterface: typeof import('./components/ChatInterface.vue')['default']
    ChatMessages: typeof import('./components/ChatMessages.vue')['default']
    CheckoutDialog: typeof import('./components/checkoutDialog.vue')['default']
    DatePicker: typeof import('./components/DatePicker.vue')['default']
    Disclaimer: typeof import('./components/Disclaimer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    LineChartComponent: typeof import('./components/LineChartComponent.vue')['default']
    Loader: typeof import('./components/loader.vue')['default']
    ModifyApptDialog: typeof import('./components/ModifyApptDialog.vue')['default']
    OrderDialog: typeof import('./components/OrderDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Schedule: typeof import('./components/schedule.vue')['default']
    Service: typeof import('./components/Service.vue')['default']
    ServiceItems: typeof import('./components/ServiceItems.vue')['default']
    TextAreaInputComponent: typeof import('./components/TextAreaInputComponent.vue')['default']
    TextInputComponent: typeof import('./components/TextInputComponent.vue')['default']
    ToastNotification: typeof import('./components/ToastNotification.vue')['default']
    TyreItem: typeof import('./components/TyreItem.vue')['default']
    TyreItems: typeof import('./components/TyreItems.vue')['default']
    VehicleInProfile: typeof import('./components/vehicle-in-profile.vue')['default']
  }
}
