/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about-us': RouteRecordInfo<'/about-us', '/about-us', Record<never, never>, Record<never, never>>,
    '/account': RouteRecordInfo<'/account', '/account', Record<never, never>, Record<never, never>>,
    '/carts': RouteRecordInfo<'/carts', '/carts', Record<never, never>, Record<never, never>>,
    '/Checkout': RouteRecordInfo<'/Checkout', '/Checkout', Record<never, never>, Record<never, never>>,
    '/contact-us': RouteRecordInfo<'/contact-us', '/contact-us', Record<never, never>, Record<never, never>>,
    '/location': RouteRecordInfo<'/location', '/location', Record<never, never>, Record<never, never>>,
    '/product': RouteRecordInfo<'/product', '/product', Record<never, never>, Record<never, never>>,
    '/services': RouteRecordInfo<'/services', '/services', Record<never, never>, Record<never, never>>,
    '/tyres': RouteRecordInfo<'/tyres', '/tyres', Record<never, never>, Record<never, never>>,
    '/your-profile': RouteRecordInfo<'/your-profile', '/your-profile', Record<never, never>, Record<never, never>>,
    '/yourprofile': RouteRecordInfo<'/yourprofile', '/yourprofile', Record<never, never>, Record<never, never>>,
  }
}
