/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about_us': RouteRecordInfo<'/about_us', '/about_us', Record<never, never>, Record<never, never>>,
    '/About_us': RouteRecordInfo<'/About_us', '/About_us', Record<never, never>, Record<never, never>>,
    '/Checkout': RouteRecordInfo<'/Checkout', '/Checkout', Record<never, never>, Record<never, never>>,
    '/contact_us': RouteRecordInfo<'/contact_us', '/contact_us', Record<never, never>, Record<never, never>>,
    '/product': RouteRecordInfo<'/product', '/product', Record<never, never>, Record<never, never>>,
  }
}
